### ISSUE TITLE
popstate event doesn't fire in IE/Edge

### ISSUE THREAD

**Issue by desperate-man** [router5/router5-history#4]
I've noticed an issue on IE and Edge browsers when I try to navigate to a URL clicking on a link such as this one `<a href="#/somepage" />` or simply changing the address in the address bar the listener registered here `window.addEventListener('popstate', fn)` never fires, but `window.addEventListener('hashchange', fn)` fires the registered event perfectly allowing users to click links with hashes and changing addresses directly, so what are the advantages of using 'popstate' instead of 'hashchange'? Why can't we register only 'hashchange' event?

**Comment by troch** [comment]
So with links and the router, you are suppose to perform some link interception (click event handlers or click event delegation). Popstate events would normally fire on back button / forward button / manual URL change (for back and forward, if there is an history entry to pop).

History is a side-effect of routing, hence why it is a plugin: it will update the history on successful routing events emitted by the router, and it will convert popstate events to routing instructions. This plugin allows the use of hash or not.

If you have a need for hashchange based routing (because you are using browsers not supporting HTML5 history API), you are welcome to create a plugin.

**Comment by desperate-man** [comment]
Alright, thanks a lot for the explanation. I will modify the history plugin for my needs.
