### ISSUE TITLE
History back to 404 route bug

### ISSUE THREAD

**Issue by hellosmithy** [router5/router5-history#8]
If `defaultRoute` is left undefined/null in the router config and 404 pages are handled by checking for a `transitionError.code` of `"ROUTE_NOT_FOUND"` and rendering a custom 404 view there is a bug when you transition away from the 404 catch-all route to a valid route, then transition back to the 404 page with the  browser back button.

Doing so triggers an `onPopState` in router5-history which in turn calls `router.navigate` with an undefined `defaultRoute` value here: https://github.com/router5/router5-history/blob/master/modules/index.js#L32.

This causes the `route-node` package to choke on `routeName.split('.')` here: https://github.com/troch/route-node/blob/master/modules/RouteNode.js#L112.

A quick fix is to define `defaultRoute` as an empty string but this doesn't seem correct behaviour.

**Comment by troch** [comment]
Related to router5/router5#68 and router5/router5#65

You are experiencing problems because your 404 page is not a state of your browser, and your app is not in sync with your browser history.

I'm currently working on router5@4.0.0 release which will include a way to deal with unknown routes, as mentioned in this comment: https://github.com/router5/router5/issues/65#issuecomment-238395938. It should provide a way to handle 404s without having to resort to hacks around the default route.

**Comment by hellosmithy** [comment]
@troch Makes sense thanks. https://github.com/router5/router5/issues/65#issuecomment-238395938 looks good. What's the expected timeline for v4?

**Comment by troch** [comment]
End of the month, maybe sooner.

**Comment by troch** [comment]
v4.0.0 has been released: http://router5.github.io/docs/migration-4.html.

See http://router5.github.io/docs/migration-4.html#unknown-routes-not-found-supported: with the option `allowNotFound` and without a set default route, the router will output a state for not found routes.

This repository is going to be deprecated. Code has been moved to main repo.

```js
import historyPlugin from 'router5-history';
```

becomes

```js
import browserPlugin from 'router5/plugins/browser';
```
